### ISSUE TITLE
How can change user interface to English?

### ISSUE THREAD

**Issue by AlyoshaMa** [ssysm/ArcTime-Translation#1]
How can change user interface to English?
怎么修改成英语?现在还不能？

**Comment by ssysm** [comment]
您好
现在此项目正在工作阶段
目前ArcTime的UI语言是嵌在程序里面的
我们需要等待开发者整理语言包
谢谢您的支持
Hi,
This Project is still under construction 
ArcTime's UI Language Pack are still inside the main application
We need to wait the separate Language Pack from the developer 
Thanks for supporting this project.
